name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    name: Image Docker
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2
      -

        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -

        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -

        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: olopes/meu-site:latest
  helm:
      needs: docker
      name: helm Install
      runs-on: ubuntu-latest
      steps:
      -
        name: Create file Cluster
        run:  mkdir ${HOME}/.kube
      -
        name: Set Kubeconfig in file
        run:  echo ${{ secrets.KUBECONFIG}} | base64 --decode > ${HOME}/.kube/config
      -
        name: Def Cluster
        run: export KUBECONFIG=$(pwd)/KubeConfig
      -
        name: Install Chart
        run: helm upgrade -i wc-lucas-olopes ./Chart --create-namespace -n wc-lucas-olopes